// <auto-generated />
using ApnaGhar.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace ApnaGhar.Web.Api.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20171126094838_Init_CheckRelations")]
    partial class Init_CheckRelations
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ApnaGhar.Models.Lookups.LookupCity", b =>
                {
                    b.Property<int>("CityID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CityDesc");

                    b.Property<string>("CityName");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<int>("CreatedBy");

                    b.Property<DateTime>("ModifiedAt");

                    b.Property<int>("ModifiedBy");

                    b.Property<int>("StateID");

                    b.HasKey("CityID");

                    b.HasIndex("StateID");

                    b.ToTable("LookupCity");
                });

            modelBuilder.Entity("ApnaGhar.Models.Lookups.LookupContinent", b =>
                {
                    b.Property<int>("ContinentID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CountryDesc");

                    b.Property<string>("CountryName");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<int>("CreatedBy");

                    b.Property<DateTime>("ModifiedAt");

                    b.Property<int>("ModifiedBy");

                    b.HasKey("ContinentID");

                    b.ToTable("LookupContinent");
                });

            modelBuilder.Entity("ApnaGhar.Models.Lookups.LookupCountry", b =>
                {
                    b.Property<int>("CountryID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ContinentID");

                    b.Property<string>("CountryDesc");

                    b.Property<string>("CountryName");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<int>("CreatedBy");

                    b.Property<DateTime>("ModifiedAt");

                    b.Property<int>("ModifiedBy");

                    b.HasKey("CountryID");

                    b.HasIndex("ContinentID");

                    b.ToTable("LookupCountry");
                });

            modelBuilder.Entity("ApnaGhar.Models.Lookups.LookupState", b =>
                {
                    b.Property<int>("StateID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CountryID");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<int>("CreatedBy");

                    b.Property<DateTime>("ModifiedAt");

                    b.Property<int>("ModifiedBy");

                    b.Property<string>("StateDesc");

                    b.Property<string>("StateName");

                    b.HasKey("StateID");

                    b.HasIndex("CountryID");

                    b.ToTable("LookupState");
                });

            modelBuilder.Entity("ApnaGhar.Models.Session.UserLoginChannels", b =>
                {
                    b.Property<int>("LoginChannelID");

                    b.Property<int>("UserID");

                    b.Property<DateTime>("CreatedAt");

                    b.HasKey("LoginChannelID", "UserID");

                    b.ToTable("UserLoginChannels");
                });

            modelBuilder.Entity("ApnaGhar.Models.Lookups.LookupCity", b =>
                {
                    b.HasOne("ApnaGhar.Models.Lookups.LookupState")
                        .WithMany("LookupCity")
                        .HasForeignKey("StateID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ApnaGhar.Models.Lookups.LookupCountry", b =>
                {
                    b.HasOne("ApnaGhar.Models.Lookups.LookupContinent")
                        .WithMany("LookupCountry")
                        .HasForeignKey("ContinentID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ApnaGhar.Models.Lookups.LookupState", b =>
                {
                    b.HasOne("ApnaGhar.Models.Lookups.LookupCountry")
                        .WithMany("LookupState")
                        .HasForeignKey("CountryID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
